/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini.projet;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;



public class Main_Home extends javax.swing.JFrame {
    public static Institution Esi = null;
    public static ArrayList<TP_Salle> salles = new ArrayList<>();
    public static int Current_Salle_TP_Index = 0;
    

    
    public static void Institution_init(){
        String logo="https://www.esi-sba.dz/fr/wp-content/uploads/2020/10/Logo-Complet-ESI-SBA-200mm-x-200mm_couleur-500x500.png";
        
        Institution Esi = new Institution (0,"High School","8 Mai 1945-Sidi-bel-abbes","+21348749452",logo);
        
        
        Department second_cycle = new Department("4","second cycle","code","Amrane abdelkader","contact_sc@esi-sba.dz");
        Department preparatory_class = new Department("4","preparatory class","code","Aced","contact_pre@esi-sba.dz");
        
        Department departements[] = {second_cycle,preparatory_class};
        
        // creation of one service the teaching service
        Service TeachingServise = new Service_Teaching("Schedule","EnrolledStrudents","30/04/2023","30/05/2023");
        
        Block block_A1 = new Block("A1", "left", "white");
        Amphitheater AmphiA = new Amphitheater(0, "Amphi D", 100.0, 1000, true);
        
        second_cycle.setBlock(block_A1);
        
         Esi.setDepartment(departements);
         
         Main_Home.Esi = Esi;
    };
    
    public static void Tp_salles_init(){
        TP_Salle Salle_TP = new TP_Salle("20 Tables", 0, "Salle TP 01", 20.0, 20);
        // creating of set of computers and one datashow
        Materials PC1 = new Pc("i7", "16G", "AC255-GGH-20", "03-01-2022","");
        Materials PC2 = new Pc("i5", "32G", "AC2F5-ALH-15", "03-01-2022","");
        Materials PC3 = new Pc("i3", "4G", "ACHK5-HGH-19", "03-01-2022","");
        Materials PC4 = new Pc("i9", "16G", "DFRTG-DGE-17", "03-01-2022","");
        Materials datashow = new Datashow("Epson", "1122352512", "03-01-2022","");
        Materials printer = new Printer("1122352512", "03-01-2022","");
        // add the matiriels to our Tp salle
        Salle_TP.add_material_to_TPSalle(PC1);
        Salle_TP.add_material_to_TPSalle(PC2);
        Salle_TP.add_material_to_TPSalle(PC3);
        Salle_TP.add_material_to_TPSalle(PC4);
        Salle_TP.add_material_to_TPSalle(datashow);
        Salle_TP.add_material_to_TPSalle(printer);
        
        Esi.departments[0].setTp_salle(salles);
        
        salles.add(Salle_TP);
    };
    
    public void load_Departements() {
        for (int i = 0; i < Esi.departments.length; i++) {
              DepartementCompobox.addItem(Esi.departments[i].DepartementName);
        }
    }
    
    public static void load_Salles(){
        DefaultListModel MyLstModel = new DefaultListModel();
        String n = DepartementCompobox.getSelectedItem().toString();

        if (n.equals("second cycle")){
            salles = Esi.departments[0].getTp_salle();
        }else if (n.equals("preparatory class")){
            salles = Esi.departments[1].getTp_salle();
        }
        
         MyLstModel.clear();
        for (TP_Salle salle : salles) {
            MyLstModel.addElement(salle.building_name);
        }
        TP_Salles_Jlist.setModel(MyLstModel);
    };
    
    public static void print_salle_materials(ArrayList<Materials> tp_materials){
        DefaultTableModel model = (DefaultTableModel) Material_Table_Affiche.getModel();

        if (tp_materials.isEmpty()) {
            model.setRowCount(0);
        } else {

            model.setRowCount(tp_materials.size());
            for (Materials tp_material : tp_materials) {
                model.removeRow(0);
                Object[] rowData = {tp_material.registration_number, tp_material.date_installtion, "",tp_material.type};
                model.addRow(rowData);
                tp_material.print_material_infos();
            } 
        }
    };
    
    
    public Main_Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        Institution_init();
        load_Departements();
        Tp_salles_init();
        load_Salles();
    //    print_salle_materials(salles.get(0).materials);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DepartementCompobox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TP_Salles_Jlist = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        head = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Material_Table_Affiche = new javax.swing.JTable();
        saveMaterials = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DepartementCompobox.setBackground(new java.awt.Color(0, 127, 255));
        DepartementCompobox.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        DepartementCompobox.setForeground(new java.awt.Color(242, 242, 242));
        DepartementCompobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select departement" }));
        DepartementCompobox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepartementCompoboxMouseClicked(evt);
            }
        });
        DepartementCompobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartementCompoboxActionPerformed(evt);
            }
        });

        TP_Salles_Jlist.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        TP_Salles_Jlist.setForeground(new java.awt.Color(0, 127, 255));
        TP_Salles_Jlist.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TP_Salles_JlistAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                TP_Salles_JlistAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TP_Salles_Jlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TP_Salles_JlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TP_Salles_Jlist);

        jButton1.setBackground(new java.awt.Color(0, 127, 255));
        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("- Delete TP salle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 127, 255));
        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(242, 242, 242));
        jButton2.setText("+ Create TP Salle ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel1.setText("Name :");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel4.setText("Email adress :");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel8.setText("Code :");

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel10.setText("Head of the departement : ");

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel12.setText("Number of Services :");

        jTextField1.setBackground(new java.awt.Color(242, 242, 242));
        jTextField1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jTextField1.setText("Departement Information");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        code.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N

        head.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N

        email.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N

        number.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(email)
                            .addComponent(number)
                            .addComponent(head)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(197, 197, 197)
                        .addComponent(code)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        Material_Table_Affiche.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        Material_Table_Affiche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Registration Number", "Installation Date", "Name/cpu/ram", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Material_Table_Affiche.setAlignmentX(2.0F);
        Material_Table_Affiche.setAlignmentY(2.0F);
        Material_Table_Affiche.setGridColor(new java.awt.Color(0, 127, 255));
        Material_Table_Affiche.setPreferredSize(new java.awt.Dimension(600, 400));
        jScrollPane2.setViewportView(Material_Table_Affiche);

        saveMaterials.setBackground(new java.awt.Color(0, 127, 255));
        saveMaterials.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        saveMaterials.setForeground(new java.awt.Color(242, 242, 242));
        saveMaterials.setText("Add new material");
        saveMaterials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMaterialsActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 127, 255));
        jButton4.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(242, 242, 242));
        jButton4.setText("Delete selected Material");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 127, 255));
        jLabel6.setText("All Materials");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini/projet/logo1.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DepartementCompobox, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 84, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(saveMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DepartementCompobox, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(saveMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AddSalleTP frame2 = new AddSalleTP();
        frame2.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // quznd il se ferme pas tt se ferme
        frame2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void DepartementCompoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartementCompoboxActionPerformed
        // TODO add your handling code here:
        load_Salles();
        String n = DepartementCompobox.getSelectedItem().toString();
        name.setText(n);
        if (n.equals("second cycle")){
            name.setText(Esi.departments[0].DepartementName);
            code.setText(Esi.departments[0].Code);
            head.setText(Esi.departments[0].HeadName);
            email.setText(Esi.departments[0].Email_Address);
            number.setText(Esi.departments[0].services);
        }else if (n.equals("preparatory class")){
                        name.setText(Esi.departments[1].DepartementName);
            code.setText(Esi.departments[1].Code);
            head.setText(Esi.departments[1].HeadName);
            email.setText(Esi.departments[1].Email_Address);
            number.setText(Esi.departments[1].services);
        }
        
    }//GEN-LAST:event_DepartementCompoboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int n = Current_Salle_TP_Index;
        salles.remove(n);
        
        load_Salles();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void saveMaterialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMaterialsActionPerformed
        // TODO add your handling code here:
        AddMaterial_tp frame3 = new AddMaterial_tp();
        frame3.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // quznd il se ferme pas tt se ferme
        frame3.setVisible(true);
        
 
        
       
    }//GEN-LAST:event_saveMaterialsActionPerformed

    private void TP_Salles_JlistAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TP_Salles_JlistAncestorMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_TP_Salles_JlistAncestorMoved

    private void TP_Salles_JlistAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TP_Salles_JlistAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TP_Salles_JlistAncestorAdded

    private void TP_Salles_JlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TP_Salles_JlistMouseClicked
        // TODO add your handling code here
        int selectedTp_salle = -1;
        selectedTp_salle = TP_Salles_Jlist.getSelectedIndex();
        Current_Salle_TP_Index= selectedTp_salle;
        
        if (selectedTp_salle != -1) {
            ArrayList<Materials> tp_materials = salles.get(selectedTp_salle).materials;
            print_salle_materials(tp_materials);
        }
    }//GEN-LAST:event_TP_Salles_JlistMouseClicked

    private void DepartementCompoboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartementCompoboxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartementCompoboxMouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int index = this.Material_Table_Affiche.getSelectedRow();
        
        salles.get(Current_Salle_TP_Index).remouve_material_from_TPSalle(index);
        if (Current_Salle_TP_Index != -1) {
            ArrayList<Materials> tp_materials = salles.get(Current_Salle_TP_Index).materials;
            print_salle_materials(tp_materials);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> DepartementCompobox;
    private static javax.swing.JTable Material_Table_Affiche;
    private static javax.swing.JList<String> TP_Salles_Jlist;
    private javax.swing.JTextField code;
    private javax.swing.JTextField email;
    private javax.swing.JTextField head;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JButton saveMaterials;
    // End of variables declaration//GEN-END:variables
}
